name: TEtrimmer
channels:
  - conda-forge
  - bioconda
dependencies:
  - python 3.10
  - aliview
  - bedtools >=2.31.1
  - bioconductor-biostrings
  - blast #arm64 null # Note: Ignore clobber warnings. blast and rmblast contain some duplicate binaries.
  - cd-hit
  - emboss #arm64 null
  - ghostscript
  - hmmer
  - iqtree
  - mafft
  - nseg
  - perl
  - pfam_scan #arm64 null
  - r-base
  - r-rcpp
  - recon #arm64 null
  - repeatmasker #arm64 null
  - repeatmodeler #arm64 null
  - samtools
  - trf
  - pip
  - pip:
    - biopython
    - click
    - dataclasses
    - dill
    - joblib
    - matplotlib
    - multiprocess
    - numpy
    - pandas
    - plotly
    - pypdf2
    - regex
    - requests
    - scikit-learn
    - tk
    - urllib3
